version: '3.8'

services:
  database:
    extends:
      file: docker-compose.base.yml
      service: database
    ports:
      - 3306:3306
  php:
    extends:
      file: docker-compose.base.yml
      service: php
    ports: 
      - 80:80