name: Run tests
on: [push, pull_request]
env:
  DOCKER_CLI_VERSION: "20.10.17"
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup docker CLI
        run: |
          curl https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_CLI_VERSION}.tgz | tar xz
          sudo cp ./docker/docker /usr/bin/ && rm -rf docker && docker version
      - name: Run tests
        run: |
          docker compose up -d
          docker compose exec -w /var/www/html php php test.php
          docker compose down --volumes
