name: Run tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes"
          test-container: php
          test-command: "cd /var/www/html && php test.php"
